if: branch=master

language: node_js

node_js:
  - "10"

cache: yarn

script: yarn build

deploy:
  provider: s3
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  bucket: "periodo-visualization"
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master


